### ISSUE TITLE
Tray Triangle is missing/invisible

### ISSUE THREAD

**Issue by athenawisdoms** [epilande/yarems#11]
Hello there!

I noticed that running the boilerplate code directly gave a menubar app that has no visible tray triangle.

![image](https://user-images.githubusercontent.com/6615285/62173809-61e33780-b305-11e9-8059-d1be34565c6b.png)

To reproduce this issue, I performed the following commands commands in sequence:
 - `git clone https://github.com/epilande/yarems && cd yarems`
 - `npm install`
 - `npm run dev`

If I changed the `background` color of `.tray-triangle` to red, we can see that it is still there.

![image](https://user-images.githubusercontent.com/6615285/62173905-d1592700-b305-11e9-95b3-9a162709499a.png)

How do you think we can fix this?

**Comment by epilande** [comment]
Hey @athenawisdoms, I just did a clean install and it looks like it's working fine. 
I followed the exact steps you provided and here's a screenshot of my local dev environment:

![image](https://user-images.githubusercontent.com/3210082/62343222-c08fe900-b49e-11e9-8b2f-a7d4a3c36304.png)

Could you double check `.app-base`. From your screenshot, it looks like the `padding` on `.app-base` isn't being applied.

**Comment by athenawisdoms** [comment]
Tried to reproduce my steps again and no longer get the problem. Thank you and sorry for the confusion!
