### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by alexcroox** [epilande/yarems#2]
Firstly, thanks for adding all the react tooling around `menubar` saves me a lot of time.

I've run into the following issue when building:

`npm run build` (the docs say `prod` fyi)

```
alex@alex ~/P/yarems> npm run build

> yarems@0.0.1 build /Users/alex/Projects/yarems
> NODE_ENV=production webpack --config webpack.config.production.babel.js && electron-packager . Yarems --platform=darwin --arch=all --prune --out release --overwrite --icon ./app.icns

/Users/alex/Projects/yarems/node_modules/schema-utils/dist/validateOptions.js:40
    throw new _ValidationError2.default(ajv.errors, name);
    ^

false
```

**Comment by alexcroox** [comment]
I believe this has to do with the webpack extract plugin, specifically around css. I stripped all this away as I'm using `styled-components` and builds worked after this.

**Comment by epilande** [comment]
Hey @alexcroox, thanks for opening this issue. 
I've updated this project's dependencies and changed the styling solution from `css-modules` to `styled-components`.

You can check out the changes here:
- Update all dependencies: https://github.com/epilande/yarems/pull/3
- Switch to styled-components:  https://github.com/epilande/yarems/pull/4

**Comment by alexcroox** [comment]
Nice work! If I'd waited 4 days to start this project I would have saved a huge amount of time :D

**Comment by epilande** [comment]
Sorry I took so long to get back to you. Had one of those busy weeks last week. 

If you have any feedback or suggestions for the project, I would love to hear them. 

Also note that with those changes, I've disabled HMR (https://github.com/epilande/yarems/issues/5), I'll try to fix that sometime tonight.

**Comment by alexcroox** [comment]
Ha you don't owe me anything. I had to hack around it a bit to get it working for my project (https://github.com/alexcroox/jira-timer) but it was nice to find a lightweight boilerplate for electron and react so thanks!
